### ISSUE TITLE
4 button added as generic zwave device

### ISSUE THREAD

**Issue by henrikln** [fiLLLip/namron-homey#1]
I just added a 4 button device and the Homey app said it couldn’t find an app for the device, was added as generic device.

Attaching advanced settings screenshot.

![0467A2A6-1FCD-4B2C-8B88-891EFB66DC80](https://user-images.githubusercontent.com/2019154/71080462-7b3e3080-218d-11ea-9d0f-c46431470d7b.png)
![6E7DC137-86DD-4557-BDE4-713421FBC22E](https://user-images.githubusercontent.com/2019154/71080464-7bd6c700-218d-11ea-8d18-603ff76bb69e.png)

**Comment by mrbendiksen** [comment]
I have the same problem!

**Comment by fiLLLip** [comment]
This is very strange, as the productId here is 41734, the same as in the ROBB-smarrt plugin. The 4-button devices I had used 41744 as the productId. Just to confirm, this is the 4-button 2 channel panel? https://www.elektroimportoren.no/namron-z-wave-2-kanaler-bryter-k4/4512720/Product.html?Event=searchlist

There is another one as well, 4-button 1 channel. https://www.elektroimportoren.no/namron-z-wave-1-kanal-bryter-k4/4512713/Product.html?Event=searchlist

Edit: I see my README links to the 1 channel. I will add a integration to the 1 channel button.

**Comment by fiLLLip** [comment]
Hi again, I managed to publish the app, please test it at https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by fiLLLip** [comment]
The updates I have posted should fix this, and due to lack of response I'm closing this issue. You're welcome to reopen if that is not the case :)
