### ISSUE TITLE
Support for Z-Wave Switch 400W

### ISSUE THREAD

**Issue by asoldal** [fiLLLip/namron-homey#10]
Hi.

Is it possible to add support for the Namron Z-Wave Switch 400W (as shown in link below) to the Namron app?

https://www.elektroimportoren.no/namron-z-wave-switch-400w/4512715/Product.html?Event=livesearch

Please find attached information regarding product ID, etc.
![Screenshot_20200217_151045_app homey](https://user-images.githubusercontent.com/61148640/74661401-325c2580-5198-11ea-8565-59c1b5f8514c.jpg)
![Screenshot_20200217_151052_app homey](https://user-images.githubusercontent.com/61148640/74661405-338d5280-5198-11ea-900d-6c9c3c0d2709.jpg)

Thank you very much!

**Comment by fiLLLip** [comment]
Should be doable!

**Comment by asoldal** [comment]
Anything I can do to contribute to the process with this?

**Comment by aasmundbo** [comment]
@asoldal : I have blindly added code for the wall switch, but I must refer to @fiLLLip to make a test version for you to try out.

Alternatively, you can run the app locally by checking out this branch and use `homey app run`.

**Comment by fiLLLip** [comment]
@aasmundbo pull request is now live at https://homey.app/no-no/app/net.filllip-namron/Namron/test/
@asoldal feel free to test!

**Comment by asoldal** [comment]
Thank you so far!
I will however not be home and able to test before in a couple of weeks from now.

**Comment by aasmundbo** [comment]
No problem, the PR (and test version of the app) will wait for you unless someone else appears and can test it out and pass it earlier 😄

**Comment by asoldal** [comment]
Finally had the chance to test this today. 
The in-wall switch is added nicely by new app version (1.3.7) and status of switch can be seen changing in Homey as I use the old physical push switch on the wall. However, the in-wall switch/relay does not react when I try to turn on/off in Homey app. 

(It is exactly the same experience when using Easyhome app. With Robbsmart app the switch is not recognized.)

Any ideas? @fiLLLip @aasmundbo

**Comment by fiLLLip** [comment]
I did some explorations and compared the socket switch and the in-wall one. Removed some code and published it to https://homey.app/no-no/app/net.filllip-namron/Namron/test/
Can you test?

**Comment by asoldal** [comment]
Tested and is working fine. 
Thanks!
