### ISSUE TITLE
Namron Z-Wave Dimmer 400W 4512710

### ISSUE THREAD

**Issue by eibo68** [fiLLLip/namron-homey#15]
Dimmer is not recognized and is added as a "Enkel Z-Wave Enhet".

**Comment by fiLLLip** [comment]
@eibo68 Can you provide links to which dimmer you bought, and screenshots of the vendor/device id from Homey app?

**Comment by eibo68** [comment]
https://www.elektroimportoren.no/namron-z-wave-dimmer-400w/4512710/Product.html
![image](https://user-images.githubusercontent.com/46458535/75810445-e3fb7900-5d8a-11ea-83dd-ef7f9c268df3.png)

**Comment by eibo68** [comment]
I have it up and running now with EasyHome/Dimmer-3wire driver for homey

**Comment by fiLLLip** [comment]
Hmm, maybe they have gotten a new batch or something. If you check https://github.com/fiLLLip/namron-homey/blob/master/drivers/ZW_Dimmer_3wire/driver.compose.json you can see manufacturer id is 816, not 1080 as in your device.

**Comment by eibo68** [comment]
Jupp, just noticed that. But has it worked earlier, or is the manufaturer id from Robb/Sunricher branch?

**Comment by fiLLLip** [comment]
It's from issue #2, so a fellow user of Namron devices. I will check if we can't add a copy of the current device driver with new manufacturer ID.

**Comment by eibo68** [comment]
I see, possible different batches/hardware on the same dimmer then.

**Comment by havenstrom** [comment]
I bought one of these as well three weeks ago, and I also have 1080 as manifacture ID. Can it have an array as manifacture ID or must it be a separate device?

**Comment by fiLLLip** [comment]
> I bought one of these as well three weeks ago, and I also have 1080 as manifacture ID. Can it have an array as manifacture ID or must it be a separate device?

As far as I can read from the docs, it must be a separate product.

**Comment by havenstrom** [comment]
Here's the unit I bought: 
![image](https://user-images.githubusercontent.com/62121667/76620891-7db2eb00-652e-11ea-86a1-c3948ede7218.png)
https://www.elektroimportoren.no/namron-z-wave-dimmer-400w/4512710/Product.html?

**Comment by eibo68** [comment]
> I bought one of these as well three weeks ago, and I also have 1080 as manifacture ID. Can it have an array as manifacture ID or must it be a separate device?

Until it is supported in the Namron-Homey app, you can search for EasyHome in Homey and use that App for this device

**Comment by fiLLLip** [comment]
Hi, you can test it by using the test version of the app: https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by fiLLLip** [comment]
Released a new test version again now https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by eibo68** [comment]
Installed and tested, works for both my namron devices, 3-way dimmer 400W and wall plug. Perfect

**Comment by havenstrom** [comment]
Worked perfectly. Thanks!
