### ISSUE TITLE
Can you please add more Namron products?

### ISSUE THREAD

**Issue by sevrinrobstad** [fiLLLip/namron-homey#2]
Hi. Would it  be possible for you to add more of the Namron products?
The "Dimmer - 3 wire" and the "Remote Control 4-channel" from Robb-Smartt upstream is as far as the pictures he has the exact same products I sit here with (except for the Namron logo), but they are just recognized as simple Z-wave devices.
Attached is the info from homey when these devices are connected.
The dimmer:
![Screenshot_20200104-205503_Homey](https://user-images.githubusercontent.com/23063479/71771000-9dc59d00-2f34-11ea-872a-67f9dcd19d3e.jpg)
The remote control 4-channel:
![Screenshot_20200104-205535_Homey](https://user-images.githubusercontent.com/23063479/71771018-eed59100-2f34-11ea-8adc-62132348245e.jpg)

**Comment by sevrinrobstad** [comment]
Just a quick update - the dimmer actually works fine with Robb-smartts App, so they must be exactly the same. The remote control does not.
But anyways, it would be cleaner and nicer in all ways to have the dimmer actually recognized as a Namron. :)

**Comment by fiLLLip** [comment]
Hi, I added the two devices to the project now. Until I manage to publish the project after Homey updated all their publishing routines, it will only be in this repo. Feel free to pull down the repo and run `npm run run` to try it on your own homey (I think that is the way to do it). I don't have a Homey myself, so I cannot verify any of this working.

**Comment by sevrinrobstad** [comment]
Damn, thats quick. Thanx!!!
 I'll try to figure out how to do test it directly and report back with the result if i succeed (in testing).

**Comment by fiLLLip** [comment]
I managed to publish the app, please test it at https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by sevrinrobstad** [comment]
Nice! 
I also managed to install it directly from my computer. It seems to work like it should. Will test your app directly from homey appstore next time I get some time to play with this.
I really appreciate you doing this so quickly!

Btw,  I have another Namron device that doesn't currently work with Homey. 
This time it your upstream repository doesnt have it, but it's just a simple wallmount on/off switch. Is this possible to add as well? 

https://www.elektroimportoren.no/namron-z-wave-veggplugg/4512717/Product.html
manual with description of commands it supports :
https://www.elektroimportoren.no/docs/namron/4512717%20INSTRUCTION%20MANUAL.pdf
zw_manufacturer_id | "816"
-- | --
zw_product_type_id | "513"
zw_product_id | "53252"
zw_secure | "✓"
zw_battery | "⨯"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_SWITCH_BINARY"
zw_device_class_specific | "SPECIFIC_TYPE_POWER_SWITCH_BINARY"
zw_firmware_id | "256"
zw_application_version | "1"
zw_application_sub_version | "0"
zw_hardware_version | "1"
zw_wakeup_interval | 0
zw_wakeup_enabled | false
energy_alwayson | false
energy_value_off | null
energy_value_on | null
zw_group_1 | ""
zw_configuration_value | ""

**Comment by fiLLLip** [comment]
I referenced the comment in issue #3, and closing this as it is confirmed working :)
