### ISSUE TITLE
Update to v.1.4.0 broke wall switch devices

### ISSUE THREAD

**Issue by bmi-vi** [fiLLLip/namron-homey#20]
After this morning when the update to v1.4.0 was installed, all of my Namron Z-Wave 1 kanal bryter K4, article nr 4512713 stopped working (https://www.elektroimportoren.no/namron-z-wave-1-kanal-bryter-k4/4512713/Product.html)

In homey, I get the message "Device is unavailable". 

My other type of Namron switch does however work. The other switch is the 2 channel 4512720 called Namron Z-Wave 2 kanaler bryter K4 (https://www.elektroimportoren.no/namron-z-wave-2-kanaler-bryter-k4/4512720/Product.html)

**Comment by fiLLLip** [comment]
Hi @cybirg, sorry to hear that! Is it possible for you to take a screenshot of the ZWave device details for this? Either by going to https://developer.athom.com/tools/zwave or in the app? What I'm looking for is something like this: https://github.com/fiLLLip/namron-homey/issues/8#issuecomment-585968179

**Comment by bmi-vi** [comment]
Thank you for the quick reply. Since the device is unavailable it is not possible to look at the z wave device details in the app, that is where the "device is unavailable" message appears.

In developer mode I get the error message "Node x is unreachable". 

The following is from https://developer.athom.com/tools/devices

Property | Value
-- | --
ID | 86d26c93-67f7-4cf0-a232-56f638c4c669
Class | sensor
Driver | homey:app:net.filllip-namron — ZW_WallController_4_2
Ready | No
Available | No (No unavailable message)
Warning | No
Custom icon | No

Key | Value
-- | --
zw_node_id | "3"
zw_manufacturer_id | "816"
zw_product_type_id | "768"
zw_product_id | "41744"
zw_secure | "✓"
zw_battery | "✓"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_WALL_CONTROLLER"
zw_device_class_specific | "SPECIFIC_TYPE_BASIC_WALL_CONTROLLER"
zw_firmware_id | "771"
zw_application_version | "1"
zw_application_sub_version | "28"
zw_hardware_version | "1"
zw_wakeup_interval | 0
zw_wakeup_enabled | false
zw_group_1 | "1"
zw_group_2 | ""
Wake-up_notification | "Wake up Wall controller before save"
zw_configuration_value | ""

**Comment by fiLLLip** [comment]
> Driver | homey:app:net.filllip-namron — ZW_WallController_4_2

This is the issue, because this was removed to be replaced by `ZW_WallController_4`. I guess you have flows and whatnot set up for this. I can take it back into the app to try to fix it.

**Comment by fiLLLip** [comment]
@cybirg Can you verify with this? https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by aasmundbo** [comment]
My 2 cents on this: Since 2 similar devices were merged into one in the latest Namron app update, wouldn’t it suffice for @cybirg to delete the existing device in the app, and re-add the wall switch? Then, update the affected flows (if any).

I mean, it was a bit unfortunate that the previous Namron app had different instances of the “same” device. If @cybirg can try to re-add the wall-switch instead of @fiLLLip undoing the improvement he did recently, I think that’s a better and more maintainable solution moving forward.

*Edit: Minor rephrasing and fixing syntactical issues*

**Comment by bmi-vi** [comment]
@fiLLLip : Thanks! I installed the test version, but the devices do not re-appear. If you think @aasmundbo 's suggestion is good I can re-add the wall switches with the current production version (1.4.0) later tonight and report back.

**Comment by fiLLLip** [comment]
I think as the devices don't reappear, this is not possible to solve without re-adding the devices. This is very weird, and unfortunate though. However, it seems to be the only way :/

**Comment by bmi-vi** [comment]
Thanks, I will do that, test and report back.

**Comment by bmi-vi** [comment]
Adding the wall switch again in Homey worked perfectly, thank you for helping me out.

**Comment by fiLLLip** [comment]
Not the solution we hoped for, but glad to hear it's working!
