### ISSUE TITLE
Namron Z-Wave Dimmer 400W

### ISSUE THREAD

**Issue by ansolem** [fiLLLip/namron-homey#21]
Unable to add dimmer to Homey. 
![Screenshot_20200417-220850_Homey](https://user-images.githubusercontent.com/42617580/79610691-51742680-80f9-11ea-9c30-ae1d52d9a208.jpg)

Bought from elekteoimportøren this week. 
https://www.elektroimportoren.no/namron-z-wave-dimmer-400w/4512710/Product.html?Referer=googleshopping&gclid=Cj0KCQiAmsrxBRDaARIsANyiD1rP9WvPArRYJFelwdGjdWJRpGcQW7syS1E5pKKtEkZsgJyt88JorhkaAivZEALw_wcB&gclsrc=aw.ds&utm_campaign=googleshopping&utm_medium=na&utm_source=na&fbclid=IwAR398_ZF5DyQ8CEupO8EdSBMkuWRah1bFMSukqIxr59w1BLVuFI0XGuOlLY

**Comment by fiLLLip** [comment]
Could you link to the dimmer in question? Is the dimmer far from the homey? I have seen cases where the zwave devices would not add if the communication "jumped" over other devices. Could you pick up your homey and place it next to the dimmer and try again?

**Comment by ansolem** [comment]
Thanks for your reply. Homey is about 5 meters away from the dimmer. I placed Homey next to the dimmer and tried to add it with out luck. Tried to add through Easyhome-app, and it worked.

**Comment by fiLLLip** [comment]
Could you take a screenshot of the device details? Its much easier to add support when knowing the details 👌

**Comment by ansolem** [comment]
![Screenshot_20200417-232947_Homey](https://user-images.githubusercontent.com/42617580/79615548-5fc74000-8103-11ea-95f5-f347800a231a.jpg)

**Comment by fiLLLip** [comment]
I'm not sure how to debug this, as others have confirmed it working, and https://github.com/fiLLLip/namron-homey/blob/master/drivers/ZW_Dimmer_3wire/driver.compose.json#L39 states that the correct Manufacturer ID, Product Type ID and Product ID is in place. Is there something you can do from https://developer.athom.com/tools/zwave that would help?

**Comment by ansolem** [comment]
Thanks. All 5 of them are currently working now.
