### ISSUE TITLE
z-wave controller uses zigbee driver

### ISSUE THREAD

**Issue by olast** [fiLLLip/namron-homey#23]
Trying to add a 4 buttons wall controller. First it was added with a Namron zigbee driver. After a lot of retries with Namrom/EasyHome it is now fixed to use "homey:app:com.easyhome.mw.zigbee — ZV9001K4_DIM_G2", even when adding it as a Namron wall controller.

Have another wall controller installed a month ago, works fine.

You may call me if you want, Filip, home office as everyone else.

**Comment by fiLLLip** [comment]
Weird! You are sure this is a ZWave controller? Please check https://developer.athom.com/tools/zwave to verify Manufacturer ID, Product ID and Product Type ID and post back :+1:

**Comment by olast** [comment]
man id: 816
prod id: 41734
prod type id: 768

And the other one works fine. (same for both)

**Comment by olast** [comment]
The old one uses
homey:app:net.filllip-namron — ZW_WallController_4
the  new on is stucked with
homey:app:com.easyhome.mw.zigbee — ZV9001K4_DIM_G2

...even when I use your app and restarts Homey before installing.

**Comment by fiLLLip** [comment]
Is it possible for you to remove/deactivate the easyhome app and try again? Not sure I can help with this problem since it touches several apps.
Our driver should match on this product:
```
		"manufacturerId": [816, 1080],
		"productTypeId": 768,
		"productId": [41734, 41744],
```

**Comment by olast** [comment]
Funny. There was a new update for easyhome three hours ago. Now it suddenly worked when I reinstalled. I will notice the others with the same error. I wasnt alone out here...
