### ISSUE TITLE
Namron ZigBee devices

### ISSUE THREAD

**Issue by espenjohannessen** [fiLLLip/namron-homey#29]
I just bought a bunch of smart home stuff, including a Homey, some Hue lightstrips and some Namron ZigBee dimmer switches tp replace my existing ones, but just now realized that this combination won't really work. I am running the experimental Homey v5 to get the Hue lightstrips to work, but there is no support for the Namron ZigBee dimmer switch. I see that you've answered to reviews on the Homey app page that support for the Namron ZigBee devices will be added as soon as v5 is released, but since the v5 release should be just around the corner, and the new SDK is ready to use, I was hoping that an updated Namron app is ready and can be used either as a final release or as a beta?

If not; do you have an ETA? Waiting for the v5 release doesn't really make sense anymore since the new SDK with improved ZigBee drivers is ready to go and can be used as is.

**Comment by fiLLLip** [comment]
Hi, this repo is for the "old" app in Homey v4.x.x. Namron has taken over ownership of the application. Even if I wanted, I can not update the app. https://github.com/fiLLLip/namron-homey/issues/26

**Comment by espenjohannessen** [comment]
Oh, OK - thanks for the update and the time you've invested in taking the app this far!
