### ISSUE TITLE
Namron Wallplug

### ISSUE THREAD

**Issue by fiLLLip** [fiLLLip/namron-homey#3]
I have another Namron device that doesn't currently work with Homey. 
This time it your upstream repository doesnt have it, but it's just a simple wallmount on/off switch. Is this possible to add as well? 

https://www.elektroimportoren.no/namron-z-wave-veggplugg/4512717/Product.html
manual with description of commands it supports :
https://www.elektroimportoren.no/docs/namron/4512717%20INSTRUCTION%20MANUAL.pdf
zw_manufacturer_id | "816"
-- | --
zw_product_type_id | "513"
zw_product_id | "53252"
zw_secure | "✓"
zw_battery | "⨯"
zw_device_class_basic | "BASIC_TYPE_ROUTING_SLAVE"
zw_device_class_generic | "GENERIC_TYPE_SWITCH_BINARY"
zw_device_class_specific | "SPECIFIC_TYPE_POWER_SWITCH_BINARY"
zw_firmware_id | "256"
zw_application_version | "1"
zw_application_sub_version | "0"
zw_hardware_version | "1"
zw_wakeup_interval | 0
zw_wakeup_enabled | false
energy_alwayson | false
energy_value_off | null
energy_value_on | null
zw_group_1 | ""
zw_configuration_value | ""

_Originally posted by @sevrinrobstad in https://github.com/fiLLLip/namron-homey/issues/2#issuecomment-570828986_

**Comment by fiLLLip** [comment]
@sevrinrobstad Could you pull down the https://github.com/fiLLLip/namron-homey/tree/feat/wallplug branch and check?

**Comment by sevrinrobstad** [comment]
This also works like a charm. Thanx again.
You should get money from Elektroimportøren :)

**Comment by fiLLLip** [comment]
Is now available in test: https://homey.app/no-no/app/net.filllip-namron/Namron/test/
