### ISSUE TITLE
Cant add Namron dimmer

### ISSUE THREAD

**Issue by peterskage** [fiLLLip/namron-homey#5]

**Comment by peterskage** [comment]
Passes the two inclusion processes, then it fails to add after some time.
![44CB028E-AAC9-47B9-8130-4D045E0BE19B](https://user-images.githubusercontent.com/35778747/72088090-cf11e480-3309-11ea-923f-13a9e19a197c.png)

**Comment by fiLLLip** [comment]
Try to exclude it and try again. You may need to login to http://developer.athom.com/ to successfully remove it. It happens sometimes, and is mostly unrelated to the app as this only binds to actions after adding.

**Comment by peterskage** [comment]
After some different approaches i managed to add it. Needed to place homey within 10cm of the device. The app works perfectly. Thanks for the great work with the app!
