### ISSUE TITLE
Namron Z-Wave 4 channel 8 button K8

### ISSUE THREAD

**Issue by egnir** [fiLLLip/namron-homey#6]
I just added a 8 button device (4channel) and the Homey app said it couldn’t find an app for the device, was added as generic device.
This device: https://www.elektroimportoren.no/namron-z-wave-4-kanaler-bryter-k8-sort/4512722/Product.html?Event=searchlist

Any plans for the Namron app to support this device in the future?

Attaching advanced settings screenshot.
![AE04953B-E6AD-411F-877F-4C3C33A23C20](https://user-images.githubusercontent.com/60109444/73134722-2ae2aa00-403a-11ea-943e-ae96dffe8421.jpeg)
![E3AF947E-AE6B-428A-8D53-BB84BCB67990](https://user-images.githubusercontent.com/60109444/73134723-2b7b4080-403a-11ea-849c-ca13bad89ab7.jpeg)

**Comment by fiLLLip** [comment]
Hi, could you join the test program and verify? https://homey.app/a/net.filllip-namron/test/

**Comment by egnir** [comment]
Takker,
Jeg skal få testet dette så snart som mulig.

Med vennlig hilsen
*Son Reklame/
Egnir WebDesign*

Ole Ringe
web designer / grafisk designer

Kontor:    6480 9030
Mobil:      9191 0161
E-post:    ole@egnir.com
Nettside: egnir.com

**Comment by egnir** [comment]
Da gikk enheten rett inn i Homey på første forsøk, og alt ser ut ril å virker som det skal:-)

Tusen takk, du må være en svært begavet fyr:-)

PS: liten skrivefeil i «black»

Med vennlig hilsen
*Son Reklame/
Egnir WebDesign*

Ole Ringe
web designer / grafisk designer

Kontor:    6480 9030
Mobil:      9191 0161
E-post:    ole@egnir.com
Nettside: egnir.com

**Comment by fiLLLip** [comment]
> Tusen takk, du må være en svært begavet fyr:-) 

Tusen takk! Kan ikke ta på meg all cred da [ROBB-smartt](https://github.com/robb-smarrt/nl.ROBBshop.ROBB-smarrt) har pløyd ferdig alt terreng.
> PS: liten skrivefeil i «black»

Fikset ;)

**Comment by egnir** [comment]
Beskjeden kar:-)
Satt i 5 timer på søndag var faktisk i gang med å lage en fork, da jeg oppdaget at kodene jeg skulle bytte var like.

Ser også at det mangler teksten i «(off)» på gruppe 5
Og så lurte på om dette panelet også har en Pressed 2x ser mange tilsvarende paneler har dette.
Uansett bare flisespikkeri. Vedlegger bilde

Med vennlig hilsen
*Son Reklame/
Egnir WebDesign*

Ole Ringe
web designer / grafisk designer

Kontor:    6480 9030
Mobil:      9191 0161
E-post:    ole@egnir.com
Nettside: egnir.com

**Comment by fiLLLip** [comment]
Ser ikke ut som vedlegget ble med. Du kan jo sjekke debug logger i homey for å se om det kommer noen events? Kan isåfall legge de til.
