### ISSUE TITLE
Support for LED Dimmer Z-Wave 200W

### ISSUE THREAD

**Issue by chrmat** [fiLLLip/namron-homey#8]
Is it possible to add support for
https://www.elektroimportoren.no/led-dimmer-z-wave-200w/1402756/Product.html

**Comment by fiLLLip** [comment]
Short answer; yes, it should be possible.
Long answer; Since I don't have a Homey myself, it's hard for me to verify any new devices working. I would need screenshots of the device id once added as a basic device, like in the other issues reported here. You would also need to the testing for me, as I'm unable to. If that is ok, I think we should be able to fix it. It's harder with this device, as the [upstream project ](https://github.com/robb-smarrt/nl.ROBBshop.ROBB-smarrt) has not added a similar device.

**Comment by fiLLLip** [comment]
Also, if you or someone who own this device (and a Homey) know how to code, pull requests are more than welcome!

**Comment by storstad** [comment]
Can’t help on the coding, but having installed 5 dimmers of the kind and using Homey, I’m happy to help & test.

**Comment by storstad** [comment]
![0A0111A4-8453-4C07-8223-ADA74F0558CE](https://user-images.githubusercontent.com/28533950/74477559-cd5cb300-4eab-11ea-8acb-b91aaa055d94.png)
![B3F1546F-19CA-4E33-9EF8-D928B293E5D0](https://user-images.githubusercontent.com/28533950/74477567-cfbf0d00-4eab-11ea-8571-eefb024516a0.png)

**Comment by aasmundbo** [comment]
I just installed my first of these LED dimmers and I can help out testing as well. I am interested in contributing, but I'm not a JS programmer nor familiar with how to develop/debug Homey apps, so figuring out that must come first. I'm probably a better tester than developer 😅 .

**Comment by fiLLLip** [comment]
If you are able, please check out the feature branch: https://github.com/fiLLLip/namron-homey/tree/feat/rotary-dimmer
Try to pull it down, have node and npm installed, run `npm run run` to test it, or something. At least that is the theory! Difficult to check when I don't own a Homey

**Comment by fiLLLip** [comment]
If you're unable, I can deploy it as a test version you can install in Homey. Just tell me :)

**Comment by aasmundbo** [comment]
I can try that branch as soon as possible. I had a stab at this myself and got it working just fine locally a few hours ago so we’re probably doing double work on this. Oh well 😅

**Comment by aasmundbo** [comment]
Basic functionality is working fine (adding to Homey, using it in flows etc.) 😄 Configuring the device isn't properly working (dimming speed, default brightness etc.). More details in the code review of the pull request.

I am trying to contribute with (in my mind) improved SVG files of the rotary dimmer, but I'm unable to push to the repo (`Permission to fiLLLip/namron-homey.git denied`). Either my git setup is wrong, or I don't have the permission, hoping the latter 😅

**Comment by fiLLLip** [comment]
> Basic functionality is working fine (adding to Homey, using it in flows etc.) 😄 Configuring the device isn't properly working (dimming speed, default brightness etc.). More details in the code review of the pull request.

Nice! Will check it out :)

> I am trying to contribute with (in my mind) improved SVG files of the rotary dimmer, but I'm unable to push to the repo (`Permission to fiLLLip/namron-homey.git denied`). Either my git setup is wrong, or I don't have the permission, hoping the latter 😅

Yeah, you don't have permission to the repo. If you fork it, you can create a PR to it.

**Comment by aasmundbo** [comment]
> Yeah, you don't have permission to the repo. If you fork it, you can create a PR to it.

I have to fork the repo, make a PR there? If I'd like to contribute to your Namron repo -- is that the way to do it? No way to get access to this repo? Sorry if it's a dumb question, I'm not used to working the "github way" (if that's a thing :smile:)

**Comment by fiLLLip** [comment]
> > Yeah, you don't have permission to the repo. If you fork it, you can create a PR to it.
> 
> I have to fork the repo, make a PR there? If I'd like to contribute to your Namron repo -- is that the way to do it? No way to get access to this repo? Sorry if it's a dumb question, I'm not used to working the "github way" (if that's a thing 😄)

Of course I can add you as a contributer :)

**Comment by fiLLLip** [comment]
@chrmat @storstad @aasmundbo Please test it before I push it to production :) https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by aasmundbo** [comment]
I’ll try ti test it tonight and get back to you.

**Comment by storstad** [comment]
In the mountains today, can test later tonight!

**Comment by aasmundbo** [comment]
I tested it briefly and it works fine.
- Adding device: 👍 
- Triggering flow from device (turn off other lights when dimmer is turned off): 👍 
- Triggering device from flow (motion set dim level to 50%): 👍 
- Configuring device options: Not tested (not really expected to work as the configuration command class parameters haven't been implemented)

I recommend to push it to production!

**Comment by storstad** [comment]
Tested yesterday, and can confirm that 4 / 5 dimmers paired just fine, and seems smooth operating 👍

However, the 5th (the one initially added as a generic Z-wave-device to add the images in this thread) doesn't pair. Successfully removed from Homey several times, but every time it insist on not being recognised as a Namron dimmer, only to be added as a generic Z-wave 🤔

I guess that is a problem related to the dimmer or Homey, but could it also have something todo with how the Namron app adds/removes devices?

**Comment by aasmundbo** [comment]
@storstad have you tried factory resetting the failing dimmer? How to do it is described in the user manual, but I think it involves pressing and holding the reset button for 5 or 10 seconds.
